### ISSUE TITLE
bug or feature? 

### ISSUE THREAD

**Issue by alexlib** [ronshnapp/MyPTV#12]
```
(myptv) PS C:\Users\alex\repos\test_cavity_myptv\example> python ../myptv/example/workflow.py .\params_file.yml matching

 given inputs -
params file name: .\params_file.yml
action: matching

Starting stereo-matching.

Traceback (most recent call last):
  File "C:\Users\alex\repos\test_cavity_myptv\myptv\example\workflow.py", line 623, in <module>
    wf = workflow(fname, action)
  File "C:\Users\alex\repos\test_cavity_myptv\myptv\example\workflow.py", line 75, in __init__
    self.do_matching()
  File "C:\Users\alex\repos\test_cavity_myptv\myptv\example\workflow.py", line 480, in do_matching
    mbf.get_particles(frames=frames)
  File "C:\Users\alex\miniconda3\envs\myptv\lib\site-packages\myptv\particle_matching_mod.py", line 161, in get_particles
    itm = initiate_time_matching(self.imsys, pd, pd1,
  File "C:\Users\alex\miniconda3\envs\myptv\lib\site-packages\myptv\particle_matching_mod.py", line 713, in __init__
    self.trees[k] = KDTree(self.pd1[k])
  File "C:\Users\alex\miniconda3\envs\myptv\lib\site-packages\scipy\spatial\_kdtree.py", line 343, in __init__
    super().__init__(data, leafsize, compact_nodes, copy_data,
  File "_ckdtree.pyx", line 567, in scipy.spatial._ckdtree.cKDTree.__init__
ValueError: data must be 2 dimensions
```

**Comment by alexlib** [comment]
please take a look at the https://github.com/alexlib/test_cavity_myptv - I probably mistyped something simple, but cannot find it.

**Comment by alexlib** [comment]
happens also in the `/myptv/example` folder

**Comment by alexlib** [comment]
my mistake
