### ISSUE TITLE
Bug - Changing segmentation method to 'dilation' missing 'particle_size'

### ISSUE THREAD

**Issue by leahmendelson** [ronshnapp/MyPTV#21]
Testing the `dilation` segmentation method with otherwise default values throws NameError. Particle_size may not be extracted correctly from the `params_file.yml`?

Operating System: Windows 10
Python Version: Miniconda3 Conda 4.12.0 Python 3.9.7

Parameters:
```
- segmentation:
    Number_of_images: 1
    images_folder: Calibration
    single_image_name: cal2.tif
    image_extension: '.tif'
    mask: 1.0
    ROI: 227, 1050, 120, 920
    plot_result: True
    threshold: 42
    median: 5
    blur_sigma: None
    local_filter: None
    min_xsize: 1.0
    min_ysize: 1.0
    min_mass: 60.0
    max_xsize: 15.0
    max_ysize: 15.0
    max_mass: None
    method: dilation 
    particle_size: 8
    save_name: None
```

Error:
```
Traceback (most recent call last):
  File "MyPTV\example\workflow.py", line 719, in <module>
    wf = workflow(fname, action)
  File "MyPTV\example\workflow.py", line 76, in __init__
    self.do_segmentation()
  File "MyPTV\example\workflow.py", line 429, in do_segmentation
    if method=='dilation' and type(particle_size) != int:
NameError: name 'particle_size' is not defined
```

**Comment by ronshnapp** [comment]
Thanks, I fixed the bug.
